sudo: required

services:
  - docker

before_install:
  - npm install vnu-jar
  - sudo mkdir build
  - sudo chmod 777 build

script:
  - docker-compose run jekyll jekyll build
  - java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html --errors-only --filterfile tests/config/vnufilter.txt build/
